newbit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('about/', views.about, name="about"),
    path('topic/<int:article_id>/', views.topic, name="topic"),
    path('topic/<int:article_id>/article', views.article, name="article"),
]

pages/templates/pages/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>TopicTitle</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">
    <style>p.indent{ padding-right: 1.3em }</style>
    <style>
    .chart-container{
    max-width: 236px;
    }
    .wrap{
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    }
    html, body {
    height:100%;
    width:100%;
    margin:0;
    padding:0;
    }
    #myChart {
    height:100%;
    width:100%;
    min-height:150px;
    }
    .zc-ref {
    display:none;
    }

    </style>
    <style type="text/css">

</head>
<meta charset="UTF-8">
<title>Title</title>
</head>
<style>
    html,body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .navbar{
        height:110px;
    }
</style>
<body>

 <div class="row d-flex justify-content-center mt-5 mb-5">
    <div class="container mt-10">
        <div>
            <h1>{{ article.title }}</h1>
            <p>{{ article.content }}</p>
        </div>
    </div>
 </div>

</body>
</html>

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">
    <link href="https://fonts.googleapis.com/css?family=Cute+Font|Gamja+Flower|Do+Hyeon|East+Sea+Dokdo|Jua|Song+Myung&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/font-nanum/1.0/nanumbarungothic/nanumbarungothic.css">
    <style>
    p.indent{ padding-right: 1.3em }
    html,body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .navbar{
        height:110px;
    }
        .chart-container{
  max-width: 400px;
}
.wrap{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
        html, body {
            height:100%;
            width:100%;
            margin:0;
            padding:0;
        }

        #myChart {
            height:100%;
            width:200%;
            min-height:150px;

        }

        .zc-ref {
            display:none;
            }
        table.type09 {
    border-collapse: collapse;
    text-align: left;
    line-height: 1.5;

}
table.type09 thead th {
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    color: #369;
    border-bottom: 3px solid #036;
}
table.type09 tbody th {
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    border-bottom: 1px solid #ccc;
    background: #f3f6f7;
}
table.type09 td {
    width: 350px;
    padding: 10px;
    vertical-align: top;
    border-bottom: 1px solid #ccc;
}


hr { border-top:1px solid #9C9C9C; border-bottom:1px solid #F6F6F6; }


select {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  outline: 0;
  box-shadow: none;
  border: 0 !important;
  background: #2c3e50;
  background-image: none;
}
/* Remove IE arrow */
select::-ms-expand {
  display: none;
}
/* Custom Select */
.select {
  position: relative;
  display: flex;
  width: 20em;
  height: 3em;
  line-height: 3;
  background: #2c3e50;
  overflow: hidden;
  border-radius: .25em;
}
select {
  flex: 1;
  padding: 0 .5em;
  color: #fff;
  cursor: pointer;
}
/* Arrow */
.select::after {
  content: '\25BC';
  position: absolute;
  top: 0;
  right: 0;
  padding: 0 1em;
  background: #34495e;
  cursor: pointer;
  pointer-events: none;
  -webkit-transition: .25s all ease;
  -o-transition: .25s all ease;
  transition: .25s all ease;
}
/* Transition */
.select:hover::after {
  color: #f39c12;
}
{% block head %}
{% endblock %}
</style>
</head>

<body>

<nav id="navbar" class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <div class="p-2">
        <a href="/"><img class="" src="/static/img/logo_black.png" height="80px" alt="" style="-webkit-filter: invert(100%)"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <!--      <a class="nav-item nav-link active mx-4" href="{% url 'pages:dashboard' %}">Home<span class="sr-only">(current)</span></a>-->
            <a class="nav-item nav-link {%if request.resolver_match.url_name == 'index'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:index' %}';">Home<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link {%if request.resolver_match.url_name == 'dashboard'%}active{%endif%} mx-4" onclick="window.location='{% url 'pages:dashboard' %}'+window.location.search;">Chart<span class="sr-only">(current)</span></a>

        </div>
    </div>
</nav>

<div class="row">
    <div class="col-12 mt-3 mb-3 d-flex justify-content-around">
        <div class="card">
            <div class="card-header d-flex justify-content-around">
<!--                &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;검색어&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;비교검색어-->
                <p>검색어</p>
                <p>비교검색어</p>
            </div>
            <div class="card-body" style="width:70rem;">
            <section class="d-flex justify-content-around">
                <div class="select">
                        <select id="slct" onchange="getSelectedValue()">
                            <option selected disabled>{{query1}}</option>
                            {% for o in query %}<option value="{{o}}">{{o}}</option>{% endfor %}
                        </select>
                </div>
                <div class="select">
                        <select id="slct2" onchange="getSelectedValue2()">
                            <option selected disabled>{{query2}}</option>
                            {% for o in query %}<option value="{{o}}">{{o}}</option>{% endfor %}
                        </select>
                </div>
                </section>
            </div>
        </div>
    </div>
</div>

<!--<div class="row d-flex align-items-center" >-->
<!--    <div class="col-12 mt-3 d-flex justify-content-around ">-->
<!--        <form  method="GET" style="visiblity:hidden">-->
<!--            <div class="col d-flex justify-content-center align-items-stretch" style="">-->
<!--                <div>-->
<!--                    <input type="search" class="input" style="text-align: center" autocomplete="off" name="q1" id="q1" value="{{query1}}" required/>-->
<!--                </div>-->
<!--                <div>-->
<!--                    <input type="search" class="input" style="text-align: center" autocomplete="off" autofocus="on" name="q2" id="q2" {% if query2 %}value="{{query2}}" {% endif %}>-->
<!--                </div>-->
<!--                <div>-->
<!--                    <button type="submit" class="search-button"><i class="fa fa-search-plus fa-2x" ></i></button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->
<!--</div>-->




<div class="d-flex align-items-stretch justify-content-center mt-2">
    <nav aria-label="breadcrumb">
        <form method="get" name="cat">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}">전체</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=경제">경제</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=IT_과학">IT_과학</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=지역">지역</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=사회">사회</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=문화">문화</a></li>
            <li class="breadcrumb-item"><a href="/dashboard/?q1={{query1}}{% if query2 %}&q2={{query2}}{% endif %}&cat=국제">국제</a></li>
        </ol>
        </form>
    </nav>
</div>

<section class="p-5">
<div class="d-flex justify-content-center d-flex align-items-center" >
    <div class="card mx-2 " style="width: 15rem; height:20rem;border:0px; border-radius: 2%">
        <div class="card-body" style="box-shadow: 0px 10px 10px 0 #263248;" >
        <div class="d-flex justify-content-center p-3">
            <img class="" src="/static/img/notepad.png" height="90px" alt="신문기사" style="opacity:0.7;">
        </div>
        <div class="p-2"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif; text-justify:bottom ;text-align: center;font-weight: bold; font-size:20px">Articles</h5>
        </div>
        <div>
            <p class="card-text" style="text-align: center;position:absolute; left:50px;bottom: 25px;">총{% if query2 %}{{sum1}}{% else %}{{num1}}{% endif %} 개의 기사를<br>크롤링하여 수집, 분석</p>
        </div>
        </div>
    </div>
    <div class="card mx-2" style="width: 15rem;height:20rem;border:0px;border-radius: 2%">
        <div class="card-body" style="box-shadow: -3px 10px 10px 0 #263248;" >
        <div class="d-flex justify-content-center p-3">
            <img src="/static/img/timeline2.png" height="90px" alt="기간" style="opacity:0.7;">
        </div>
        <div class="p-2"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif; text-align: center;font-weight: bold; font-size:20px;">Period</h5>
        </div>
        <div>
            <p class="card-text"  style="text-align: center;position:absolute; left:50px;bottom: 25px;">2009년 1월 1일부터<br>2019년까지의 기사<br></p>
        </div>
        </div>
    </div>
    <div class="card mx-2" style="width: 15rem;height:20rem; border:0px;border-radius: 2%">
        <div class="card-body" style="box-shadow: -4px 10px 10px 0 #263248;" > <!--  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24) -->
        <div class="d-flex justify-content-center p-3">
            <img class="mx-5 px-5" src="/static/img/office.png" height="90px" alt="신문사"style="opacity:0.7;">
        </div>
        <div class="p-2"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif;text-align: center; font-weight: bold; font-size:20px">Media</h5>
        </div>
        <div>
            <p class="card-text"  style="text-align: center;position:absolute; left:35px;bottom: 25px;">19개의 언론사<br>(중앙지 11社, 경제지 8社)</p>
        </div>
        </div>
    </div>
    <div class="card mx-2" style="width: 15rem;height:20rem; border:0px;border-radius: 2%">
        <div class="card-body" style="box-shadow: -4px 10px 10px 0 #263248;" > <!--  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24) -->
        <div class="d-flex justify-content-center p-3">
            <img class="mx-5 px-5" src="/static/img/chat.png" height="90px" alt="토픽" style="opacity:0.7;">
        </div>
        <div class="p-2"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif;text-align: center; font-weight: bold; font-size:20px">Topics</h5>
        </div>
        <div>
            <p class="card-text"  style="text-align: center;position:absolute; left:40px;bottom: 13px;">{% if query2 %}{{sum1}}{% else %}{{num1}}{% endif %}개의 기사를<br>8개의 카테고리로 분류 후<br>{% if query2 %}{{sum2}}{% else %}{{num2}}{% endif %}개의 토픽으로 세분화</p>
        </div>
        </div>
    </div>
</div>
</section>

{% block body %}
{% endblock %}


<script>
    function getSelectedValue()
    {
        var selectedValue = document.getElementById("slct").value;
        document.location.href = '/dashboard/?q1='+ selectedValue {% if query2 %} + '&q2={{query2}}' {% endif %}
    }
    function getSelectedValue2()
    {
        var selectedValue2 = document.getElementById("slct2").value;
        document.location.href = '/dashboard/?q1={{query1}}&q2='+ selectedValue2
    }

</script>


</body>
</html>

pages/templates/pages/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">

    <title>Document</title>
    <style>



html, body {
  background: #F5BA45;
  font-family: 'Noto Sans KR', sans-serif;
}
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  outline: 0;
  box-shadow: none;
  border: 0 !important;
  background: #2c3e50;
  background-image: none;
}
/* Remove IE arrow */
select::-ms-expand {
  display: none;
}
/* Custom Select */
.select {
  position: relative;
  display: flex;
  width: 20em;
  height: 3em;
  line-height: 3;
  background: #2c3e50;
  overflow: hidden;
  border-radius: .25em;
}
select {
  flex: 1;
  padding: 0 .5em;
  color: #fff;
  cursor: pointer;
}
/* Arrow */
.select::after {
  content: '\25BC';
  position: absolute;
  top: 0;
  right: 0;
  padding: 0 1em;
  background: #34495e;
  cursor: pointer;
  pointer-events: none;
  -webkit-transition: .25s all ease;
  -o-transition: .25s all ease;
  transition: .25s all ease;
}
/* Transition */
.select:hover::after {
  color: #f39c12;
}
</style>

</head>
<body>
<section class="p-4">
<div style="position: relative; ">
    <a href="/"><img class="" src="/static/img/logo_black.png" height="80px" alt="logo" style=""></a>
</div>
</section>
<section class="p-5"></section>
<section class="p-3 m-5">
<div class="d-flex align-items-center justify-content-center">
    <a class="mx-4 px-5" style="font-family: 'Libre Baskerville', serif;  font-size:35px; font-weight: bold ;text-align: center; word-spacing: 10px ;letter-spacing:3px">Build your new insight with us</a>
</div>
<div class="d-flex align-items-center justify-content-center">

    <a class="mx-4 px-5" style="font-family: 'Old Standard TT', serif; text-align: center;  font-size:20px;">All you want is here <br>
Exploring a web new trend, and being a leader</a>
</div>
</section>
<section class="p-1 m-3">

</section>

<section class="d-flex justify-content-around">
    <div class="select">
    <select id="slct" onchange="getSelectedValue()">
    <option selected disabled>Choose an option</option>
    {% for i in query %}<option value="{{i}}">{{i}}</option>{% endfor %}
    </select>
    </div>
</section>


<div class="p-5 m-5">
<div class="d-flex justify-content-center" >
    <div class="card mx-2 " style="width: 15rem; height:20rem;border:0px; border-radius: 2%">
        <div class="card-body" style="box-shadow: 0px 10px 10px 0 #263248;" >
        <div class="d-flex justify-content-center p-5">
            <img src="/static/img/infographic.png" height="50px" alt="" style="opacity:0.7;">
        </div>
        <div class="p-3"></div>
        <div>
        <h5 class="card-title" style="font-family:'Dosis', sans-serif; text-justify:bottom ;text-align: center; font-weight: bold; font-size:20px">Categorization</h5>
        </div>
        <div>
        <p class="card-text overflow-auto" style="text-align: center;position:absolute; left:40px;bottom: 25px;">카테고리 별 대표기사를<br> 추출하여 중복 기사 제거</p>
        </div>
        </div>
    </div>
    <div class="card mx-2" style="width: 15rem;height:20rem;border:0px;border-radius: 2%">
        <div class="card-body" style="box-shadow: -3px 10px 10px 0 #263248;" >
        <div class="d-flex justify-content-center p-5">
            <img class="mx-5 px-5" src="/static/img/timeline (1).png" height="60px" alt="" style="opacity:0.7">
        </div>
        <div class="p-3"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif; text-align: center; font-weight: bold; font-size:20px;">Timeline</h5>
        </div>
        <div>
            <p class="card-text"  style="text-align: center;position:absolute; left:40px;bottom: 13px;">대표 기사 빈도를 <br>시간순으로 출력하여<br> 중요기사 선별 기능 제공</p>
        </div>
        </div>
    </div>
    <div class="card mx-2" style="width: 15rem;height:20rem; border:0px;border-radius: 2%">
        <div class="card-body" style="box-shadow: -4px 10px 10px 0 #263248;" > <!--  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24) -->
        <div class="d-flex justify-content-center p-5">
            <img class="mx-5 px-5" src="/static/img/graph.png" height="50px" alt=""style="opacity:0.7">
        </div>
        <div class="p-3"></div>
        <div>
            <h5 class="card-title" style="font-family: 'Dosis', sans-serif;text-align: center; font-weight: bold; font-size:20px">Visualization</h5>
        </div>
        <div>
            <p class="card-text"  style="text-align: center;position:absolute; left:40px;bottom: 13px;">한 번의 클릭으로<br> 기업 관련 뉴스 트렌드를 <br>시각화하여 제공</p>
        </div>
        </div>
    </div>
</div>
</div>
<script>
    function getSelectedValue()
    {
        var selectedValue = document.getElementById("slct").value;
        document.location.href = '/dashboard/?q1='+ selectedValue
    }
</script>
</body>
</html>

pages/templates/pages/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Kaushan+Script|Dosis|Noto+Sans+KR|Libre+Baskerville|Old+Standard+TT&display=swap">
    <style>
        .tag {
text-transform: uppercase;
position: relative;
line-height: 2.5em;
padding: 0 1em;
display: inline-block;
}


.tag-colored {
background-color: #9a9ba1;
color: #fff;
}

.tag:before,
.tag:after {
content: "";
height: 1px;
/* any width higher than the widest part of the page */
width: 1000px;
position: absolute;
top: 50%;
display: block;
}

hr { border-top:1px solid #9C9C9C; border-bottom:1px solid #F6F6F6; }
        .chart-container {
            max-width: 236px;
        }

        .wrap {
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
        }

        #myChart {
            height: 100%;
            width: 100%;
            min-height: 150px;
        }

        .zc-ref {
            display: none;
        }

    </style>
    <style>
    .chart-container{
    max-width: 236px;
    }
    .wrap{
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    }
        html, body {
            height:100%;
            width:100%;
            margin:0;
            padding:0;
        }
        #myChart {
            height:100%;
            width:100%;
            min-height:150px;
        }
        .zc-ref {
            display:none;
        }

    </style>
    <style type="text/css">

hr { border-top:1px solid #9C9C9C; border-bottom:1px solid #F6F6F6; }

</head>
<meta charset="UTF-8">
<title>Title</title>
</head>
<style>
    html,body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .navbar{
        height:110px;
    }
</style>
    <style>
    p.indent{ padding-right: 1.3em }
    html,body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .navbar{
        height:110px;
    }
    .chart-container{
  max-width: 400px;
}
.wrap{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
        html, body {
            height:100%;
            width:100%;
            margin:0;
            padding:0;
        }

        #myChart {
            height:100%;
            width:200%;
            min-height:150px;

        }

        .zc-ref {
            display:none;
            }
        table.type09 {
    border-collapse: collapse;
    text-align: left;
    line-height: 1.5;

}
table.type09 thead th {
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    color: #369;
    border-bottom: 3px solid #036;
}
table.type09 tbody th {
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    border-bottom: 1px solid #ccc;
    background: #f3f6f7;
}
table.type09 td {
    width: 350px;
    padding: 10px;
    vertical-align: top;
    border-bottom: 1px solid #ccc;
}


</style>
<body>

<nav id="navbar" class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <div style="position: absolute; top:15px; left:-50px">
        <a href="/"><img class="mx-5 px-5 d-flex justify-content-start" src="/static/img/logo_black.png" height="80px" alt="" style="-webkit-filter: invert(100%)"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        </div>
    </div>
</nav>


<div class="container">
    <div class="mt-5 mb-5">
        <div><p style="font-family: 'Nanum Barun Gothic';"> 키워드 : {{ article.query }} </p></div>
        <div><p style="font-family: 'Nanum Barun Gothic';"> 카테고리 : {{ article.cat_selected }} </p></div>
        <hr/>
    </div>

    <!-- 1st row-->
    <div class="row d-flex justify-content-center mt-5 mb-5">
        <div class="col-5 mt-10">
            <!--word cloud-->
            <div id="myChart7"></div>
            <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
            <script src="https://cdn.zingchart.com/zingchart-core.min.js"></script>
            <script>zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";</script>
            <script>
                ZC.LICENSE = ["b55b025e438fa8a98e32482b5f768ff5"];
                var myConfig = {
                    type: 'wordcloud',
                    options: {
                        text: '{{ word_cloud3 }}',
                        ignore: ['&#39', '금지&#39']
                    }
                };

                zingchart.render({
                    id: 'myChart7',
                    data: myConfig,
                    height: 400,
                    width: '100%'
                });
            </script>
        </div>
        <!--기사본문가져오기-->
        <div class="col-7 mt-10">
               <div>
                <h1>{{ article.title }}</h1>
                <p>{{ article.content }}</p>
            </div>
        </div>
    </div>

    <!-- 2nd row-->
    <div class="row d-flex justify-content-center mt-5 mb-5">
        <!--기사목록불러오기-->
        <div class="col-12 mt-10">
            <div class="row mt-5 mb-5 d-flex justify-content-center">
                <table class="type09">
                    <thead>
                        <tr>
                            <th scope="cols" style="width: 100px;">날짜</th>
                            <th scope="cols" style="width: 400px;">기사제목</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in same_topic %}
                     <tr>
                         <th>{{ i.date.year }}-{{i.date.month}}-{{i.date.day }}</th>
                         <th><a href="{% url 'pages:article'  i.id%}" onclick="window.open(this.href, '_blank', 'left=250, top=100, width=600, height=720, toolbars=no ,scrollbars=no'); return false;">{{i.title}}</a></th>
                     </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<!--    차트 끝-->

    <div class="col-6 offset-3 mt-5">
        <div id="myChart7"></div>
        <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
        <script src="https://cdn.zingchart.com/zingchart-core.min.js"></script>
        <script>zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";</script>
        <script>
            ZC.LICENSE = ["b55b025e438fa8a98e32482b5f768ff5"];
            var myConfig = {
                type: 'wordcloud',
                options: {
                    text: '{{ word_cloud3 }}',
                    ignore: ['&#39', '금지&#39']
                }
            };

            zingchart.render({
                id: 'myChart7',
                data: myConfig,
                height: 400,
                width: '100%'
            });
        </script>


    </div>
</div>
</body>
</html>